### PR TITLE
Add failing test case

### PR DESCRIPTION
**Pull request by gnom7**
* add failing test case

### CODE REVIEW

**Comment by mpalourdio** [comment]
Meh :| that's unfortunate. I suppose it was failing before the last refactoring

**Comment by mpalourdio** [comment]
I mean, all those timing features are hard to grasp. That's why I am very precocious before introducing them :/

**Comment by mpalourdio** [comment]
I have just tested against V3, and the test succeeds. So this is a regression

**Comment by mpalourdio** [comment]
Oh, of course, that's the (not) famous ``return EMPTY`` that did the job !

**Comment by mpalourdio** [comment]
Not sure how the `merge(showSpinner, hideSpinner)` fixes the problem ? Can you explain me ? I fail at rxjs here :D

**Comment by gnom7** [comment]
I agree, we should test this a lot before pushing.

**Comment by mpalourdio** [comment]
merging for now anyway. But if you ever have an explanation on the fix :+1:

**Comment by mpalourdio** [comment]
I have added more tests in this [PR](https://github.com/mpalourdio/ng-http-loader/pull/94). It includes all your changes, documentation and more.

**Comment by gnom7** [comment]
@mpalourdio I will try to explain, so the issue was that `debounceDelay` delayed time when spinner starts to be visible, but what if request ends before spinner is shown? `showSpinner` observable will emit in either case, so `switchMap` helps in a way that when `hideSpinner` emits it will unsubscribe from observable which was delayed and will re-subscribe once more to listen further. Also, we need to add here (`merge`) `showSpinner` so that first time show event is triggered we do not miss it just because we still haven't `hideSpinner` observable emissions.

**Comment by mpalourdio** [comment]
Got it, that's the cancel 'feature' of switchMap that does the job. Hope this will go well :D

**Pull request merged**
