### PR TITLE
use ReplaySubject for pendingRequestsStatus

### PR DESCRIPTION
**Pull request by amitport**
so when I subscribe during a request I get the current status

### CODE REVIEW

**Comment by mpalourdio** [comment]
Can you be a bit more specific please ? Adding a test that show the expected behavior/use-case would help too.

**Comment by amitport** [comment]
use case:
load a page component that have a long http request in the constructor
sub component that need to show the loading indicator loads later, but the first notification it will see will be `false` and the request ended

workaround:
```
this.isWorking = pendingRequestInterceptorService.pendingRequests !== 0;
this.subscription = pendingRequestInterceptorService.pendingRequestsStatus
                                  .subscribe(hasPendingRequests => {
                                          this.isWorking= hasPendingRequests;
                                   });
```
workaround2: make all http request in AfterContentInit hook

In any case, I'm not sure how to build a test here, sorry

**Comment by mpalourdio** [comment]
"long" http requests should not be a problem as they are non blocking (because asynchronous).

What you mean is that, in your case,  when the spinner component loads, you have performed n first http request, but the value has not been emitted because the subscriber was not ready ? Correct me if I'm wrong. What are those cases ? Lazy loaded modules ?

I need to take a little more time to think about his ``replaySubject``. The problem is : if you subscribe manually for whatever reason AND automatically by loading the ``SpinnerComponent`` in your app, both subscribers will receive ALL emitted events, what could lead to strange problems.

**Comment by amitport** [comment]
> "but the value has not been emitted because the subscriber was not ready"

yes

> "What are those cases ? Lazy loaded modules ?"

no need for something that complex, just put your spinner-component inside of a component that make a long request in the constructor. It will miss the initial 'true' status event

> both subscribers will receive ALL emitted events

it's just set to `ReplaySubject(1)` so only the last event will trigger immediately on each new subscription. if it's false it will have not effect, but we want to make sure we get 'true' if we missed it.

**Comment by mpalourdio** [comment]
> it's just set to ReplaySubject(1) so only the last event will trigger immediately on each new subscription. if it's false it will have not effect, but we want to make sure we get 'true' if we missed it.

Fair point. Need to test it myself. I'd like this point covered by a test. I will maybe PR your branch those next days.

**Comment by mpalourdio** [comment]
I have just made a quick test, and I wanted to let you know that I can easily reproduce what you mentioned.

Just wondering if it's not cleaner (or safer) to change Subject by BehavorSubject, rather than ReplaySubject. In any case, the ``_pendingRequestsStatus`` will hold only one value in the case (true or false).

I tried by replacing Subject by BehaviorSubject and It fixed the problem. I just need a little time to write a failing test to master.

**Comment by amitport** [comment]
Yeah `BehaviorSubject` is probably cleaner (the only difference is that it will always emit on subscribe, while `ReplaySubject(1)` will only emit if there was at least one event)

**Comment by mpalourdio** [comment]
So let's go with ReplaySubject for the moment. Thanks for contributing !

**Comment by mpalourdio** [comment]
V0.5.1 with this fix has just been released.

**Pull request merged**
